In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Step 2: Importing dataset**

In [ ]:
df = pd.read_csv("/content/Data.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [ ]:
df.shape

(10, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
df.sort_values("Age")

Country   Age   Salary Purchased
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
5   France  35.0  58000.0       Yes
9   France  37.0  67000.0       Yes
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
0   France  44.0  72000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
6    Spain   NaN  52000.0        No

In [ ]:
# since there are only 2 null values, we can drop it

df = df.dropna()

**Step 4: Encoding categorical data**

In [ ]:
le = LabelEncoder()

country_le = le.fit_transform(df['Country'])
df.Country = country_le

purchased_le = le.fit_transform(df['Purchased'])
df.Purchased = purchased_le

df

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
5        0  35.0  58000.0          1
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

**Step 5: Creating a dummy variable**

In [ ]:
pd.get_dummies(df)

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
5        0  35.0  58000.0          1
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

**Step 6: Splitting the datasets into training sets and Test sets**

In [ ]:
X = df[["Country","Age","Salary"]].values
y = df.Purchased.values

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

**Step 7: Feature Scaling**

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)
print(X_test_scaled)

[[ 1.22474487  0.04271788 -0.27444156]
 [-1.22474487 -0.08543577  0.24555298]
 [ 1.22474487 -1.36697225 -1.40109641]
 [ 0.          1.58056167  1.63220509]
 [-1.22474487  0.81163977  0.67888176]
 [ 0.         -0.98251131 -0.88110187]]
[[-1.22474487  1.32425437  1.28554207]
 [-1.22474487 -0.34174306 -0.53443884]]
